### ISSUE TITLE
Helicone Async fails on integrating with Vocode

### ISSUE THREAD

**Issue by paddy4050** [Helicone/helicone#1425]
**NOTES**
Using helicone_async with vocode to so as to able to view the metrics of the data received from open AI

**Suggested Modifications**
* The file `helicone_python/openai_async/openai_injector.py` needs to be modified  as below:-

```
async for item in result:
    # Process each item here
    # You can add 'helicone_meta' to each item if they are dictionary-like objects
    item["helicone_meta"] = helicone_meta
```

Where previously  below code was being used 

```
result["helicone_meta"] = helicone_meta
TypeError: 'async_generator' object does not support item assignment
```

**Comment by dakshgup** [comment]
The `TypeError: 'async_generator'` object does not support item assignment occurs because the `async_generator` object, which you get from an asynchronous iteration (async for), yields items one at a time and does not support direct item assignment like a dictionary or list would. In Python, generators (including async generators) are designed to produce a sequence of items one at a time, and they do not support indexing or direct modification of the items they yield.

In the original code snippet you provided, attempting to directly modify the result object like `result["helicone_meta"] = helicone_meta` assumes result is a dictionary or a similar data structure that supports item assignment, which is not the case here. result is an `async_generator`, which means it's a stream of data that you can only interact with by iterating over it.

The suggested modification correctly addresses this issue by asynchronously iterating over each item yielded by the result async generator. Within the loop, you can modify each item assuming it's a dictionary-like object that supports item assignment. Here's a corrected approach based on your suggestion:

```python
async def generator_intercept_packets():
    response = {}
    response["streamed_data"] = []
    async for r in result:  # Correctly using async for to iterate over async generator
        r["helicone_meta"] = helicone_meta  # Assuming r is a dictionary-like object
        response["streamed_data"].append(json.loads(r.__str__()))
        yield r
    send_response(response)
```

This approach works under the assumption that each r yielded by the result async generator is a mutable object like a dictionary, which supports item assignment. If `r` is not a dictionary and does not support item assignment, you would need to transform it into a dictionary or another mutable structure before adding the helicone_meta key.

Remember, when working with async generators in Python, you must use async for to iterate over the items they yield, and you can only modify those items if they are mutable and support item assignment.
