### ISSUE TITLE
Pipe to custom domain (Azure OpenAI service support)

### ISSUE THREAD

**Issue by chitalian** [Helicone/helicone#213]
Taken from https://github.com/Helicone/helicone/discussions/139

Azure has the ability for users to [deploy their own OpenAI service](https://azure.microsoft.com/en-us/products/cognitive-services/openai-service#faq) as part of their cognitive services offerings. By the looks of it, Microsoft will quickly mirror functionality and models as they're made available by OpenAI (e.g. they added chat-turbo the day after it was available).

See below example from the OpenAI cookbook on how the Azure OpenAI endpoints look. Users give their deployment a name and end up with https://my-service-name.openai.azure.com. No indication that this url pattern will change, but not sure.

https://github.com/openai/openai-python/blob/main/README.md#microsoft-azure-endpoints

Potential options:

Pass in the Azure endpoint along with the rest of the Helicone params
Or setup something in the UI for users to specify which API key should go where (either create an Azure service record or send to OpenAI)

> updated documentation link, need to provide api_type, api_base and api_version

Credit: @aavetis

**Comment by aavetis** [comment]
this would be great, as many teams are getting Azure credits (startups, individuals, nonprofits) and this could apply towards them

**Comment by alexkreidler** [comment]
Looks like support for this is available now in the libraries and with the API via the `Helicone-OpenAI-Api-Base` header. It would be great to include in the docs the fact that this works for any custom OpenAI-compatible domain, and can be used via regular HTTP headers and doesn't **require** the library, because the docs [currently omit those details and focus just on Azure OpenAI](https://docs.helicone.ai/examples/azure-openai). Maybe rename the docs page Custom API/Base URLs?

**Comment by chitalian** [comment]
Azure support: https://docs.helicone.ai/getting-started/integration-method/azure
