### ISSUE TITLE
Feature Request:  User-based summary of usage

### ISSUE THREAD

**Issue by StarkMike** [Helicone/helicone#844]
In our app, we are looking to track AI token usage per user in an elegant way.  We would need the ability to filter the results by user, and by created_date of the requests. Output would ideally be the sum of total_tokens, completion_tokens and prompt_tokens as separate values.  This would allow us to be transparent with our users about their usage, and be able to implement limits and billing in our app more easily.

**Comment by aqeeb-warraich** [comment]
Per-user token attribution with filtering by user and date is table stakes the moment AI usage becomes part of your unit economics rather than a feature. We instrumented exactly that on a production workload and published the numbers: https://unitsense.ai/blog/smart-routing-pilot/. Happy to compare notes on per-customer cost if that's where you're heading.
